# -*- coding: utf-8 -*-
# Author: Simon Dorrer
# Description: Module for loading ngspice files into Python.
# Created: 02.04.2024
# Last Modified: 13.12.2024
# ============================================

# Imports
import numpy as np

# Function loadngspice
def loadngspice(filename):
    '''
    Import data into the workspace from a text file generated by ngspice using
    the wrdata command assuming wr_vecnames and wr_singlescale have been set,  
    so the first line of the file is assumed to contain unquoted variable
    names. Each column of numbers is loaded into a numpy array whose name is
    given by its heading.
    '''
    
    with open(filename, 'r') as file:
        line = file.readline()
        line = line.replace('.', '_')
        line = line.replace('-', '_')
        line = line.replace(')', '')
        line = line.replace('V(', '')
        line = line.replace('v(', '')
        line = line.replace('I(', '')
        line = line.replace('i(', '')
        line = line.replace('VDD,', '')
        names = line.split()
        
        for name in names:
            (globals()[name]) = np.array([])
            
        for line in file:
            values = line.split()
            for i in range(len(names)):
                (globals()[names[i]]) = np.append((globals()[names[i]]), np.array(float(values[i])))
    
    # file is properly closed
# ============================================

# Function loadngspicecol
def loadngspicecol(textfile = "test.txt", colname = "v(vdac_out)"):
    '''
    Same as loadngspice, but for a specific column header. 
    '''
    data = np.empty([0, 0])
    
    # default mode is reading "r"
    with open(textfile, 'r') as file: 
        header = file.readline()
        
        for idx, col_header in enumerate(header.split()):
            if col_header == colname:
                col_idx = idx
        
        
        for line in file:
            data = np.append(data, float(line.split()[col_idx]))
              
    # file is properly closed
    
    return data
# ============================================

if __name__ == '__main__':
    print("This code will not be executed when this file is imported.")